root: true
extends:
  - eslint:recommended
env:
  es6: true
  commonjs: true
  browser: true
  node: true
rules:
	no-unused-vars: false
parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns: 
  - src/styles/**
  - src/css/**
  - src/scss/**
  - src/sass/**
  - src/style/**
  - src/assets/**
  - public